acceuil_newsletter:
    resource: "@AcceuilBundle/Controller/NewsletterController.php"
    type:     annotation

acceuil_news:
    resource: "@AcceuilBundle/Controller/NewsController.php"
    type:     annotation

acceuil_user:
    resource: "@AcceuilBundle/Controller/UserController.php"
    type:     annotation

acceuil_post:
    resource: "@AcceuilBundle/Controller/PostController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

acceuil_admin:
    resource: "@AcceuilBundle/Controller/AdminController.php"
    type:     annotation

acceuil_default:
    resource: "@AcceuilBundle/Controller/DefaultController.php"
    type:     annotation

acceuil_custom:
    resource: "@AcceuilBundle/Controller/CustomController.php"
    type:     annotation
