# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        user:
            entity: { class: AcceuilBundle\Entity\User }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs


        main:
            anonymous: ~

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_MEMBRE
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
          main:
              pattern: ^/
              form_login:
                  provider: _provider
                  login_path:  login
                  check_path:  login_check
                  csrf_token_generator: security.csrf.token_manager
              logout:
                  path:   logout
              logout: true
              anonymous: true
          dev:
              pattern: ^/(_(profiler|wdt)|css|images|js)/
              security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
