# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
   User.class: AcceuilBundle\Entity\User

services:
   UserListener:
       class: AcceuilBundle\EventListener\UserListener
       arguments: ["@fos_user.user_manager","@doctrine.orm.entity_manager"]
       tags:
            - { name: kernel.event_subscriber }

   authentication.handler.login_success_handler:
       class:  AcceuilBundle\Security\LoginSuccessHandler
       arguments:  ['@router', '@security.authorization_checker']
