<?php

namespace AcceuilBundle\Repository;

/**
 * CustomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomRepository extends \Doctrine\ORM\EntityRepository
{
}
